CREATE TABLE `Foods` ( `Id` INT NOT NULL AUTO_INCREMENT , `Name` VARCHAR(300) NOT NULL , `Material` VARCHAR(3000) NOT NULL , `Price` DOUBLE NOT NULL , `Off` DOUBLE NULL , PRIMARY KEY (`Id`)) ENGINE = MyISAM;

ALTER TABLE `Foods` ADD `BinImage` LONGBLOB NOT NULL AFTER `Off`;

ALTER TABLE `Foods` ADD `Type` VARCHAR(50) NOT NULL AFTER `BinImage`;

ALTER TABLE `Foods` CHANGE `BinImage` `BinImage` LONGBLOB NULL;
ALTER TABLE `Foods` CHANGE `Off` `Off` DOUBLE NULL;

ALTER TABLE `Foods` ADD `Rating` DOUBLE NULL AFTER `Type`;