CREATE TABLE `Lotteries` (
  `Id` int(11) NOT NULL,
  `Name` varchar(300) NOT NULL,
  `Date` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `Lotteries`
  ADD PRIMARY KEY (`Id`);

ALTER TABLE `Lotteries`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `Lotteries` ADD `IsActive` BIT(1) NOT NULL AFTER `Date`;

ALTER TABLE `Lotteries` CHANGE `IsActive` `IsActive` BIT(1) NULL;

ALTER TABLE `Lotteries` CHANGE `Date` `Date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;