CREATE TABLE `Orders` ( `Id` BIGINT NOT NULL AUTO_INCREMENT , `FactorId` INT NOT NULL , `FoodId` INT NOT NULL , `BranchId` INT NOT NULL , `Count` SMALLINT NOT NULL , PRIMARY KEY (`Id`)) ENGINE = InnoDB;

ALTER TABLE `Orders` ADD `PriceOff` DOUBLE NOT NULL AFTER `Count`;
ALTER TABLE `Orders` ADD `PriceScalar` DOUBLE NOT NULL AFTER `Count`;

ALTER TABLE `Factors` ADD `CouponCode` INT NOT NULL AFTER `Status`;